Create a compiler script for quickfix
When you use :GodotRun, you get output in your quickfix. Some of it has
useful error messages. With this compiler, you can jump directly to
those errors.

Godot outputs filenames including res:// and we match those directly
which works because of godot#edit_res_path from 970be76.

Example output that it can parse:

SCRIPT ERROR: Parse Error: Unexpected "Identifier" in class body.
          at: GDScript::reload (res://mainmenu/scene_transition.gd:5)
ERROR: Failed to load script "res://mainmenu/scene_transition.gd" with error "Parse error".
   at: load (modules/gdscript/gdscript.cpp:2788)
SCRIPT ERROR: Parse Error: Could not preload resource script "res://shared/input/device_icons.gd".
          at: GDScript::reload (res://mainmenu/eggplant.gd:6)
ERROR: Failed to instantiate an autoload, script 'res://mainmenu/eggplant.gd' does not inherit from 'Node'.
   at: (main/main.cpp:3207)
SCRIPT ERROR: Invalid call to function 'get_world_cellv' in base 'TileMap (gridworld.gd)'. Expected 2 arguments.
          at: _process (res://games/drop_walker/code/player.gd:73)

Parsed into:

res://mainmenu/scene_transition.gd|5 error| Parse Error: Unexpected "Identifier" in class body.
res://mainmenu/scene_transition.gd|| Parse error
res://mainmenu/eggplant.gd|6 error| Parse Error: Could not preload resource script "res://shared/input/device_icons.gd".
res://mainmenu/eggplant.gd|| does not inherit from 'Node'.
res://games/drop_walker/code/player.gd|73 error| Invalid call to function 'get_world_cellv' in base 'TileMap (gridworld.gd)'. Expected 2 arguments.